name: Update status on project board
on:
  #repository_dispatch:
  #  types: [status_update]
  issues:
    types: [ closed ]
  pull_request:
    types: [ closed ]
jobs:
  update_project:
    runs-on: ubuntu-latest
    steps:
      - name: Update status
        id: update_status
        uses: github/update-project-action@v2
        with:
          github_token: ${{ secrets.STATUS_UPDATE_TOKEN }}
          organization: SnabbGET
          project_number: 1
          content_id: ${{ github.event.issue.node_id || github.event.pull_request.node_id }}
          # ${{ github.event.client_payload.command.resource.id }}
          field: 0..10
          value: -1
